### ISSUE TITLE
[bug] nan arrays can be written but not read

### ISSUE THREAD

**Issue by darienmorrow** [untzag/tidy_headers#16]
MWE:
```
    import tidy_headers
    import numpy as np
    import pathlib
    import collections
    here = pathlib.Path.cwd()    
    filepath = here / 'tidytest.txt'
    outdict = collections.OrderedDict() 
    arr = np.array([np.nan])
    outdict['foo'] = arr
    tidy_headers.write(filepath, outdict)
    indict = tidy_headers.read(filepath)
```
stdout error message upon evaluation of the last line
```
runfile('C:/Users/darien/source/test.py', wdir='C:/Users/darien/source')
Traceback (most recent call last):

  File "C:\Users\darien\source\test.py", line 27, in <module>
    indict = tidy_headers.read(filepath)

  File "C:\ProgramData\Miniconda3\lib\site-packages\tidy_headers-1.0.2-py3.7.egg\tidy_headers\_main.py", line 60, in read
    headers[key] = string2item(split[1])

  File "C:\ProgramData\Miniconda3\lib\site-packages\tidy_headers-1.0.2-py3.7.egg\tidy_headers\_parse_item.py", line 100, in string2item
    split = [ast.literal_eval(i) for i in split]

  File "C:\ProgramData\Miniconda3\lib\site-packages\tidy_headers-1.0.2-py3.7.egg\tidy_headers\_parse_item.py", line 100, in <listcomp>
    split = [ast.literal_eval(i) for i in split]

  File "C:\ProgramData\Miniconda3\lib\ast.py", line 91, in literal_eval
    return _convert(node_or_string)

  File "C:\ProgramData\Miniconda3\lib\ast.py", line 90, in _convert
    return _convert_signed_num(node)

  File "C:\ProgramData\Miniconda3\lib\ast.py", line 63, in _convert_signed_num
    return _convert_num(node)

  File "C:\ProgramData\Miniconda3\lib\ast.py", line 55, in _convert_num
    raise ValueError('malformed node or string: ' + repr(node))

ValueError: malformed node or string: <_ast.Name object at 0x0000020B37D25208>
```

**Comment by darienmorrow** [comment]
May be related to https://bugs.python.org/issue15245

**Comment by darienmorrow** [comment]
Specifically, the problem is in evaluations like `ast.literal_eval('nan')`

There is a draft PEP sponsored by Guido that is considering fixing this problem. https://github.com/CadeBrown/peps/blob/master/pep-9999.rst
