### ISSUE TITLE
string2item for tuples

### ISSUE THREAD

**Issue by ksunden** [untzag/tidy_headers#4]
```
>>> tidy_headers._parse_item.string2item('(1, 2, 3)', sep=', ')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    tidy_headers._parse_item.string2item('(1, 2, 3)', sep=', ')
  File "/usr/lib/python3.5/site-packages/tidy_headers/_parse_item.py", line 100, in string2item
    split = [ast.literal_eval(i) for i in split]
  File "/usr/lib/python3.5/site-packages/tidy_headers/_parse_item.py", line 100, in <listcomp>
    split = [ast.literal_eval(i) for i in split]
  File "/usr/lib/python3.5/ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    (1
     ^
```

**Comment by ksunden** [comment]
Note, if the "sep" is not commas, but the tuple is still comma delineated, this reads in fine
