### ISSUE TITLE
Parsing strings which contain colons

### ISSUE THREAD

**Issue by ksunden** [untzag/tidy_headers#5]
If there is a value in a key value pair which contains a colon, an error is returned by `item_to_string`

e.g. when parsing this line in a file:
```
# data info:    'PMT560 ND180 note: PMT probably more like 650'
```
I get the following error:
```
>>> d = wt.data.from_PyCMDS('data_files/tsf/cn_1585/superhi.data')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    d = wt.data.from_PyCMDS('data_files/tsf/cn_1585/superhi.data')
  File "/home/kyle/wright/WrightTools/WrightTools/data/_pycmds.py", line 53, in fr
om_PyCMDS
    headers = tidy_headers.read(filepath)
  File "/usr/lib/python3.6/site-packages/tidy_headers/_main.py", line 43, in read
[39m
    headers[key] = string2item(split[1])
  File "/usr/lib/python3.6/site-packages/tidy_headers/_parse_item.py", line 100, in 
6mstring2item
    split = [ast.literal_eval(i) for i in split]
  File "/usr/lib/python3.6/site-packages/tidy_headers/_parse_item.py", line 100, in 
6m<listcomp>
    split = [ast.literal_eval(i) for i in split]
  File "/usr/lib64/python3.6/ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib64/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    'PMT560 ND180 note
```
Work around for now is to delete the colon from the file

**Comment by ksunden** [comment]
Hmmm, Does not seem to be true of all colons, timestamps and urls both contain colons and parse fine

**Comment by untzag** [comment]
I'll have to think about this one...

I'm thinking it will be true for all colons followed by whitespace
